version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: gardner
      POSTGRES_PASSWORD: gardner
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
